export const GET_CLOSEST_SHOWS_REQUEST = "GET_CLOSEST_SHOWS_REQUEST";
export const GET_CLOSEST_SHOWS_SUCCESS = "GET_CLOSEST_SHOWS_SUCCESS";
export const GET_CLOSEST_SHOWS_ERROR = "GET_CLOSEST_SHOWS_ERROR";

export const GET_PAST_SHOWS_REQUEST = "GET_PAST_SHOWS_REQUEST";
export const GET_PAST_SHOWS_SUCCESS = "GET_PAST_SHOWS_SUCCESS";
export const GET_PAST_SHOWS_FAILURE = "GET_PAST_SHOWS_FAILURE";

export const GET_SHOW_DETAILS_REQUEST = "GET_SHOW_DETAILS_REQUEST";
export const GET_SHOW_DETAILS_SUCCESS = "GET_SHOW_DETAILS_SUCCESS";
export const GET_SHOW_DETAILS_FAILURE = "GET_SHOW_DETAILS_FAILURE";