export const GET_CLOSEST_SHOWS_REQUEST = "GET_CLOSEST_SHOWS_REQUEST";
export const GET_CLOSEST_SHOWS_SUCCESS = "GET_CLOSEST_SHOWS_SUCCESS";
export const GET_CLOSEST_SHOWS_ERROR = "GET_CLOSEST_SHOWS_ERROR";