export const GET_CLOSEST_SHOWS_REQUEST = "GET_CLOSEST_SHOWS_REQUEST";
export const GET_CLOSEST_SHOWS_SUCCESS = "GET_CLOSEST_SHOWS_SUCCESS";
export const GET_CLOSEST_SHOWS_FAILURE = "GET_CLOSEST_SHOWS_FAILURE";

export const GET_PAST_SHOWS_REQUEST = "GET_PAST_SHOWS_REQUEST";
export const GET_PAST_SHOWS_SUCCESS = "GET_PAST_SHOWS_SUCCESS";
export const GET_PAST_SHOWS_FAILURE = "GET_PAST_SHOWS_FAILURE";

export const GET_SHOW_DETAILS_REQUEST = "GET_SHOW_DETAILS_REQUEST";
export const GET_SHOW_DETAILS_SUCCESS = "GET_SHOW_DETAILS_SUCCESS";
export const GET_SHOW_DETAILS_FAILURE = "GET_SHOW_DETAILS_FAILURE";

export const CREATE_SHOW_REQUEST = "CREATE_SHOW_REQUEST";
export const CREATE_SHOW_SUCCESS = "CREATE_SHOW_SUCCESS";
export const CREATE_SHOW_FAILURE = "CREATE_SHOW_FAILURE";

export const UPDATE_SHOW_REQUEST = "UPDATE_SHOW_REQUEST";
export const UPDATE_SHOW_SUCCESS = "UPDATE_SHOW_SUCCESS";
export const UPDATE_SHOW_FAILURE = "UPDATE_SHOW_FAILURE";

export const DELETE_SHOW_REQUEST = "DELETE_SHOW_REQUEST";
export const DELETE_SHOW_SUCCESS = "DELETE_SHOW_SUCCESS";
export const DELETE_SHOW_FAILURE = "DELETE_SHOW_FAILURE";

export const GET_SHOWS_CONTAINING_BY_SONG_REQUEST = "GET_SHOW_CONTAINING_BY_SONG_REQUEST";
export const GET_SHOWS_CONTAINING_BY_SONG_SUCCESS = "GET_SHOWS_CONTAINING_BY_SONG_SUCCESS";
export const GET_SHOWS_CONTAINING_BY_SONG_FAILURE = "GET_SHOWS_CONTAINING_BY_SONG_FAILURE";

export const CREATE_TICKET_PAYMENT_REQUEST = "CREATE_TICKET_PAYMENT_REQUEST";
export const CREATE_TICKET_PAYMENT_SUCCESS = "CREATE_TICKET_PAYMENT_SUCCESS";
export const CREATE_TICKET_PAYMENT_FAILURE = "CREATE_TICKET_PAYMENT_FAILURE";