export const GET_ALL_PHOTOS_REQUEST = "GET_ALL_PHOTOS_REQUEST";
export const GET_ALL_PHOTOS_SUCCESS = "GET_ALL_PHOTOS_SUCCESS";
export const GET_ALL_PHOTOS_FAILURE = "GET_ALL_PHOTOS_FAILURE";

export const GET_ALL_PHOTOS_PAGINATED_SUCCESS = "GET_ALL_PHOTOS_PAGINATED_SUCCESS";

export const GET_PHOTO_COLLECTION_BY_ID_SUCCESS = "GET_PHOTO_COLLECTION_BY_ID_SUCCESS";