export const GET_ALL_PHOTOS_REQUEST = "GET_ALL_PHOTOS_REQUEST";
export const GET_ALL_PHOTOS_SUCCESS = "GET_ALL_PHOTOS_SUCCESS";
export const GET_ALL_PHOTOS_FAILURE = "GET_ALL_PHOTOS_FAILURE";

export const GET_ALL_PHOTOS_PAGINATED_REQUEST = "GET_ALL_PHOTOS_PAGINATED_REQUEST";
export const GET_ALL_PHOTOS_PAGINATED_SUCCESS = "GET_ALL_PHOTOS_PAGINATED_SUCCESS";
export const GET_ALL_PHOTOS_PAGINATED_FAILURE = "GET_ALL_PHOTOS_PAGINATED_FAILURE";


export const GET_PHOTO_COLLECTION_BY_ID_REQUEST = "GET_PHOTOCOLLECTION_BY_ID_REQUEST";
export const GET_PHOTO_COLLECTION_BY_ID_SUCCESS = "GET_PHOTO_COLLECTION_BY_ID_SUCCESS";
export const GET_PHOTO_COLLECTION_BY_ID_FAILURE = "GET_PHOTO_COLLECTION_BY_ID_FAILURE";

export const CREATE_PHOTO_COLLECTION_REQUEST = "CREATE_PHOTO_COLLECTION_REQUEST";
export const CREATE_PHOTO_COLLECTION_SUCCESS = "CREATE_PHOTO_COLLECTION_SUCCESS";
export const CREATE_PHOTO_COLLECTION_FAILURE = "CREATE_PHOTO_COLLECTION_FAILURE";

export const UPDATE_PHOTO_COLLECTION_REQUEST = "UPDATE_PHOTO_COLLECTION_REQUEST";
export const UPDATE_PHOTO_COLLECTION_SUCCESS = "UPDATE_PHOTO_COLLECTION_SUCCESS";
export const UPDATE_PHOTO_COLLECTION_FAILURE = "UPDATE_PHOTO_COLLECTION_FAILURE";

export const DELETE_PHOTO_COLLECTION_REQUEST = "DELETE_PHOTO_COLLECTION_REQUEST";
export const DELETE_PHOTO_COLLECTION_SUCCESS = "DELETE_PHOTO_COLLECTION_SUCCESS";
export const DELETE_PHOTO_COLLECTION_FAILURE = "DELETE_PHOTO_COLLECTION_FAILURE";
