export const GET_SHOP_OVERVIEW_REQUEST = 'GET_SHOP_OVERVIEW_REQUEST';
export const GET_SHOP_OVERVIEW_SUCCESS = 'GET_SHOP_OVERVIEW_SUCCESS';
export const GET_SHOP_OVERVIEW_FAILURE = 'GET_SHOP_OVERVIEW_FAILURE';

export const GET_ALL_PRODUCTS_PAGINATED_SUCCESS = 'GET_ALL_PRODUCTS_PAGINATED_SUCCESS';