export const GET_SHOP_OVERVIEW_REQUEST = 'GET_SHOP_OVERVIEW_REQUEST';
export const GET_SHOP_OVERVIEW_SUCCESS = 'GET_SHOP_OVERVIEW_SUCCESS';
export const GET_SHOP_OVERVIEW_FAILURE = 'GET_SHOP_OVERVIEW_FAILURE';

export const GET_ALL_PRODUCTS_PAGINATED_REQUEST = 'GET_ALL_PRODUCTS_PAGINATED_REQUEST';
export const GET_ALL_PRODUCTS_PAGINATED_SUCCESS = 'GET_ALL_PRODUCTS_PAGINATED_SUCCESS';
export const GET_ALL_PRODUCTS_PAGINATED_FAILURE = 'GET_ALL_PRODUCTS_PAGINATED_FAILURE';

export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS';