export const GET_ALL_RELEASES_REQUEST = "GET_ALL_RELEASES_REQUEST";
export const GET_ALL_RELEASES_SUCCESS = "GET_ALL_RELEASES_SUCCESS";
export const GET_ALL_RELEASES_FAILURE = "GET_ALL_RELEASES_FAILURE";

export const GET_RELEASE_BY_ID_REQUEST = "GET_RELEASE_BY_ID_REQUEST";
export const GET_RELEASE_BY_ID_SUCCESS = "GET_RELEASE_BY_ID_SUCCESS";
export const GET_RELEASE_BY_ID_FAILURE = "GET_RELEASE_BY_ID_FAILURE";

export const ADD_RELEASE_REQUEST = "ADD_RELEASE_REQUEST";
export const ADD_RELEASE_SUCCESS = "ADD_RELEASE_SUCCESS";
export const ADD_RELEASE_FAILURE = "ADD_RELEASE_FAILURE";

export const UPDATE_RELEASE_REQUEST = "UPDATE_RELEASE_REQUEST";
export const UPDATE_RELEASE_SUCCESS = "UPDATE_RELEASE_SUCCESS";
export const UPDATE_RELEASE_FAILURE = "UPDATE_RELEASE_FAILURE";

export const DELETE_RELEASE_REQUEST = "DELETE_RELEASE_REQUEST";
export const DELETE_RELEASE_SUCCESS = "DELETE_RELEASE_SUCCESS";
export const DELETE_RELEASE_FAILURE = "DELETE_RELEASE_FAILURE";
