export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_USER_DETAILS_REQUEST = "GET_USER_DETAILS_REQUEST";
export const GET_USER_DETAILS_SUCCESS = "GET_USER_DETAILS_SUCCESS";
export const GET_USER_DETAILS_FAILURE = "GET_USER_DETAILS_FAILURE";

export const GET_ALL_ORDERS_FAILURE = "GET_ALL_ORDERS_FAILURE";
export const GET_ALL_ORDER_REQUEST = "GET_ALL_ORDER_REQUEST";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";

export const GET_ALL_PAYMENT_DETAILS_REQUEST = "GET_ALL_PAYMENT_DETAILS_REQUEST";
export const GET_ALL_PAYMENT_DETAILS_SUCCESS = "GET_ALL_PAYMENT_DETAILS_SUCCESS";
export const GET_ALL_PAYMENT_DETAILS_FAILURE = "GET_ALL_PAYMENT_DETAILS_FAILURE";

export const GET_PAYMENT_DETAILS_BY_ID_REQUEST = "GET_PAYMENT_DETAILS_BY_ID_REQUEST";
export const GET_PAYMENT_DETAILS_BY_ID_SUCCESS = "GET_PAYMENT_DETAILS_BY_ID_SUCCESS";
export const GET_PAYMENT_DETAILS_BY_ID_FAILURE = "GET_PAYMENT_DETAILS_BY_ID_FAILURE";

export const UPDATE_PAYMENT_DETAILS_REQUEST = "UPDATE_PAYMENT_DETAILS_REQUEST";
export const UPDATE_PAYMENT_DETAILS_SUCCESS = "UPDATE_PAYMENT_DETAILS_SUCCESS";
export const UPDATE_PAYMENT_DETAILS_FAILURE = "UPDATE_PAYMENT_DETAILS_FAILURE";

export const GET_ALL_ADDRESSES_REQUEST = "GET_ALL_ADDRESSES_REQUEST";
export const GET_ALL_ADDRESSES_SUCCESS = "GET_ALL_ADDRESSES_SUCCESS";
export const GET_ALL_ADDRESSES_FAILURE = "GET_ALL_ADDRESSES_FAILURE";

export const GET_ADDRESS_DETAILS_REQUEST = "GET_ADDRESS_DETAILS_REQUEST";
export const GET_ADDRESS_DETAILS_SUCCESS = "GET_ADDRESS_DETAILS_SUCCESS";
export const GET_ADDRESS_DETAILS_FAILURE = "GET_ADDRESS_DETAILS_FAILURE";

export const UPDATE_ADDRESS_REQUEST = "UPDATE_ADDRESS_REQUEST";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS_FAILURE = "UPDATE_ADDRESS_FAILURE";

export const DELETE_ADDRESS_SUCCESS = "DELETE_ADDRESS_SUCCESS";

export const DELETE_PAYMENT_SUCCESS = "DELETE_PAYMENT_SUCCESS";

export const USER_LOGOUT = "USER_LOGOUT";

export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";