export const GET_ALL_NEWS_REQUEST = "GET_ALL_NEWS_REQUEST";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_FAILURE = "GET_ALL_NEWS_FAILURE";

export const GET_ALL_NEWS_PAGINATED_SUCCESS = "GET_ALL_NEWS_PAGINATED_SUCCESS";

export const GET_LATEST_UPDATE_BY_ID_SUCCESS = "GET_LATEST_UPDATE_BY_ID_SUCCESS";