export const GET_ALL_NEWS_REQUEST = "GET_ALL_NEWS_REQUEST";
export const GET_ALL_NEWS_SUCCESS = "GET_ALL_NEWS_SUCCESS";
export const GET_ALL_NEWS_FAILURE = "GET_ALL_NEWS_FAILURE";

export const GET_ALL_NEWS_PAGINATED_REQUEST = "GET_ALL_NEWS_PAGINATED_REQUEST";
export const GET_ALL_NEWS_PAGINATED_SUCCESS = "GET_ALL_NEWS_PAGINATED_SUCCESS";
export const GET_ALL_NEWS_PAGINATED_FAILURE = "GET_ALL_NEWS_PAGINATED_FAILURE";

export const GET_LATEST_UPDATE_BY_ID_REQUEST = "GET_LATEST_UPDATE_BY_ID_REQUEST";
export const GET_LATEST_UPDATE_BY_ID_SUCCESS = "GET_LATEST_UPDATE_BY_ID_SUCCESS";
export const GET_LATEST_UPDATE_BY_ID_FAILURE = "GET_LATEST_UPDATE_BY_ID_FAILURE";

export const ADD_LATEST_UPDATE_REQUEST = "ADD_LATEST_UPDATE_REQUEST";
export const ADD_LATEST_UPDATE_SUCCESS = "ADD_LATEST_UPDATE_SUCCESS";
export const ADD_LATEST_UPDATE_FAILURE = "ADD_LATEST_UPDATE_FAILURE";

export const UPDATE_LATEST_UPDATE_REQUEST = "UPDATE_LATEST_UPDATE_REQUEST";
export const UPDATE_LATEST_UPDATE_SUCCESS = "UPDATE_LATEST_UPDATE_SUCCESS";
export const UPDATE_LATEST_UPDATE_FAILURE = "UPDATE_LATEST_UPDATE_FAILURE";

export const DELETE_LATEST_UPDATE_REQUEST = "DELETE_LATEST_UPDATE_REQUEST";
export const DELETE_LATEST_UPDATE_SUCCESS = "DELETE_LATEST_UPDATE_SUCCESS";
export const DELETE_LATEST_UPDATE_FAILURE = "DELETE_LATEST_UPDATE_FAILURE";
