export const GET_SONG_DETAILS_REQUEST = "GET_SONG_DETAILS_REQUEST";
export const GET_SONG_DETAILS_SUCCESS = "GET_SONG_DETAILS_SUCCESS";
export const GET_SONG_DETAILS_FAILURE = "GET_SONG_DETAILS_FAILURE";

export const GET_ALL_SONGS_ORDERED_REQUEST = "GET_ALL_SONGS_ORDERED_REQUEST";
export const GET_ALL_SONGS_ORDERED_SUCCESS = "GET_ALL_SONGS_ORDERED_SUCCESS";
export const GET_ALL_SONGS_ORDERED_FAILURE = "GET_ALL_SONGS_ORDERED_FAILURE";

export const ADD_SONG_REQUEST = "ADD_SONG_REQUEST";
export const ADD_SONG_SUCCESS = "ADD_SONG_SUCCESS";
export const ADD_SONG_FAILURE = "ADD_SONG_FAILURE";

export const UPDATE_SONG_REQUEST = "UPDATE_SONG_REQUEST";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const UPDATE_SONG_FAILURE = "UPDATE_SONG_FAILURE";

export const DELETE_SONG_REQUEST = "DELETE_SONG_REQUEST";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const DELETE_SONG_FAILURE = "DELETE_SONG_FAILURE";
